// Main client export
export { UnipileClient } from './client/index.js';

// Enums
export {
  AccountStatus,
  AccountProvider,
  WebhookSource,
  WebhookEvent,
  CheckpointType,
  ErrorCategory,
  LinkedInSearchType,
} from './enums/index.js';

// Interfaces
export type {
  UnipileConfig,
  UnipileApiVersion,
  PaginatedResponse,
  PaginationOptions,
  ApiResponse,
  Attachment,
  DateRange,
  Account,
  OAuthConnectRequest,
  CredentialsConnectRequest,
  CookieConnectRequest,
  QrCodeConnectRequest,
  ImapConnectRequest,
  Checkpoint,
  CheckpointResolveRequest,
  HostedAuthLink,
  CreateHostedAuthLinkRequest,
  ReconnectAccountRequest,
  AuthIntentType,
  CreateAuthIntentRequest,
  AuthIntent,
  CreateAuthLinkRequest,
  AuthLink,
  ResolveAuthCheckpointRequest,
  EmailAddress,
  Email,
  EmailTracking,
  LinkClick,
  SendEmailRequest,
  UpdateEmailRequest,
  EmailFolder,
  ListEmailsOptions,
  CreateDraftRequest,
  EmailCompatibilityBoundary,
  ChatAttendee,
  Chat,
  Message,
  MessageDeliveryStatus,
  MessageReaction,
  StartChatRequest,
  SendMessageRequest,
  ListChatsOptions,
  ListMessagesOptions,
  SendInMailRequest,
  InMailCreditBalance,
  JsonAttachment,
  UpdateChatRequest,
  DownloadAttachmentRequest,
  LinkedInCompany,
  LinkedInPerson,
  LinkedInPosition,
  LinkedInEducation,
  LinkedInLocation,
  CompanySearchFilters,
  PeopleSearchFilters,
  CompanySearchRequest,
  PeopleSearchRequest,
  CompanySearchResult,
  PeopleSearchResult,
  SearchParameterValue,
  SearchParameterType,
  LinkedInSearchParameterV2Type,
  GetSearchParametersRequest,
  EnrichCompanyRequest,
  EnrichPersonRequest,
  LinkedInRouteGroup,
  RawLinkedInRequest,
  GetLinkedInSearchParametersV2Request,
  LinkedInSearchV2Request,
  ListPostsRequest,
  ReactToPostRequest,
  CreatePostCommentRequest,
  SendInvitationRequest,
  Webhook,
  CreateWebhookRequest,
  MessageReceivedPayload,
  MailSentPayload,
  MailOpenedPayload,
  LinkClickedPayload,
  AccountStatusChangedPayload,
  WebhookPayload,
  WebhookDelivery,
  WebhookEndpoint,
  CreateWebhookEndpointRequest,
  WebhookEventType,
} from './interfaces/index.js';

export { DEFAULT_CONFIG, DEFAULT_V2_API_BASE_URL } from './interfaces/index.js';

// Services (for advanced usage)
export {
  AccountService,
  EmailService,
  MessagingService,
  LinkedInService,
  WebhookService,
} from './services/index.js';

// HTTP client (for advanced usage)
export { HttpClient, type RequestOptions, type HttpResponse } from './http/index.js';
export { RateLimiter } from './http/index.js';

// Errors
export {
  UnipileError,
  TimeoutError,
  ConnectionError,
  RateLimitError,
  AuthError,
  ValidationError,
  NotFoundError,
  type ErrorContext,
  type ValidationErrorDetail,
} from './errors/index.js';
